apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
    - mirrors:
        - <mirror_url>:8443/openshift4
      source: registry.redhat.io/openshift4
    - mirrors:
        - <mirror_url>:8443/rhceph
      source: registry.redhat.io/rhceph
    - mirrors:
        - <mirror_url>:8443/odf4
      source: registry.redhat.io/odf4
    - mirrors:
        - <mirror_url>:8443/lvms4
      source: registry.redhat.io/lvms4
