- name: Wait for install to complete
  kubernetes.core.k8s_info:
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: "{{ metadata.name }}"
    namespace: "{{ metadata.name }}"
    wait: true
    wait_condition:
      type: Completed
      status: "True"
    wait_sleep: 60
    wait_timeout: 14400

- name: Get kubeconfig ref
  kubernetes.core.k8s_info:
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: "{{ metadata.name }}"
    namespace: "{{ metadata.name }}"
  register: aci
  until: aci.resources[0].spec.clusterMetadata.adminKubeconfigSecretRef.name is defined
  retries: 30
  delay: 60

- name: Get kubeconfig
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ aci.resources[0].spec.clusterMetadata.adminKubeconfigSecretRef.name }}"
    namespace: "{{ metadata.name }}"
  register: kubeconfig

- name: Copy kubeconfig to file
  ansible.builtin.copy:
    content: "{{ kubeconfig.resources[0].data.kubeconfig | b64decode }}"
    dest: "{{ aci.resources[0].spec.clusterMetadata.adminKubeconfigSecretRef.name }}"
    mode: "0600"
  register: kubeconfig_file

- name: Run tasks on edge cluster
  environment:
    KUBECONFIG: "{{ kubeconfig_file.dest }}"
  block:
    # this needs be be applied post-install, disabling the Console operator with an install manifest stops the installer from reporting 100% completion
    - name: ConsoleOperatorDisable
      when: (edgeCluster.disableConsole is defined) and (edgeCluster.disableConsole)
      kubernetes.core.k8s:
        definition:
          apiVersion: operator.openshift.io/v1
          kind: Console
          metadata:
            name: cluster
          spec:
            managementState: Removed
        state: present

    - name: Apply post-install manifests
      when: edgeCluster.postInstallManifestsFolder is defined
      loop: "{{ lookup('ansible.builtin.fileglob', lookup('ansible.builtin.vars', 'post_install_manifests_folder') + '/*', wantlist=True) | sort }}"
      loop_control:
        pause: 15
      kubernetes.core.k8s:
        src: "{{ item }}"
        wait: true
        state: present
      vars:
        # this var is copied in like this because ansible.builtin.vars doesn't support dicts
        post_install_manifests_folder: "{{ edgeCluster.postInstallManifestsFolder }}"

    - name: Install Storage and Registry
      when: (edgeCluster.odfStorage is defined) and (edgeCluster.odfStorage.enabled)
      block:
        - name: Install ODF
          ansible.builtin.include_role:
            name: "{{ playbook_dir }}/../common/roles/storage"
          vars:
            catalog_source: "{{ edgeCluster.odfStorage.catalogSource | default('redhat-operators') }}"

        - name: Install Image Registry
          when: (edgeCluster.odfStorage.imageRegistry is defined) and (edgeCluster.odfStorage.imageRegistry)
          ansible.builtin.include_tasks: registry.yaml
