- name: Enable HyperShift
  when: (edgeCluster.hypershift is defined) and (edgeCluster.hypershift.enabled)
  ansible.builtin.set_fact:
    hypershift: true

- name: Standard cluster post-install
  when: not hypershift
  ansible.builtin.include_tasks: standard.yaml

- name: HyperShift post-install
  when: hypershift
  ansible.builtin.include_tasks: hypershift.yaml
