- name: Check for LVMS
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: odf-lvm-operator # TODO: support LVMS
    namespace: openshift-storage
  register: lvms
  until: lvms is not failed

# have to manually create the PVC when using LVMS
# this is because the image registry attempts to create a PVC as ReadWriteMany, which LVMS doesn't support
- name: Create PVC for Image Registry
  when: lvms.resources | length | int == 1
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: registry-storage-pvc
        namespace: openshift-image-registry
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Get current Image Registry settings
  kubernetes.core.k8s_info:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
  register: image_registry
  until: image_registry is not failed

- name: Configure Image Registry
  kubernetes.core.k8s:
    template: ImageRegistry.yaml.j2
    state: present
    wait: true
    wait_timeout: 1200
    wait_condition:
      type: Available
      status: "True"
  register: k8s_result
  until: k8s_result is not failed
