- name: Check for ODF LVM
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: odf-lvm-operator
    namespace: openshift-storage
  register: odf_lvm

# have to manually create the PVC when using ODF-LVM
# this is because the image registry attempts to create a PVC as ReadWriteMany, which ODF-LVM doesn't support
- name: Create PVC for Image Registry
  when: odf_lvm.resources | length | int == 1
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: registry-storage-pvc
        namespace: openshift-image-registry
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    apply: true
    state: present

- name: Get current Image Registry settings
  kubernetes.core.k8s_info:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
  register: image_registry

- name: Configure Image Registry
  kubernetes.core.k8s:
    template: ImageRegistry.yaml.j2
    state: present
    wait: true
    wait_timeout: 1200
    wait_condition:
      type: Available
      status: "True"
