- name: Remove PVs
  kubernetes.core.k8s:
    template: PersistentVolume.yaml.j2
    state: absent
    wait: true
    wait_timeout: 1200
  loop: "{{ pv_list }}"

- name: Remove folders
  ansible.builtin.command: oc debug node/{{ first_node }} -- rm -rfv /host/var/local/{{ item.pv_name }}
  loop: "{{ pv_list }}"
  register: command_result
  changed_when: '"removed directory" in command_result.stdout'
