os_images:
  - openshiftVersion: "4.10"
    version: "4.10.37"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.11"
    version: "4.11.9"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.12"
    version: "4.12.3"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.13"
    version: "4.13.0-ec.3"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.13.0-ec.3/rhcos-4.13.0-ec.3-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
asc_db_size: 10Gi
asc_fs_size: 50Gi
asc_im_size: 50Gi
