- name: Create Namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ operator_namespace }}"
        annotations:
          workload.openshift.io/allowed: management # needed if this is being applied on a SNO server with workload partitioning
    state: present

- name: Create OperatorGroup
  kubernetes.core.k8s:
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: "{{ operator_name }}"
        namespace: "{{ operator_namespace }}"
      spec:
        targetNamespaces:
          - "{{ operator_namespace }}"
    state: present

- name: Create Subscription
  kubernetes.core.k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ operator_name }}"
        namespace: "{{ operator_namespace }}"
      spec:
        installPlanApproval: Automatic
        name: "{{ operator_name }}"
        source: "{{ catalog_source | default('redhat-operators') }}"
        sourceNamespace: openshift-marketplace
    state: present
  register: create_sub

- name: Wait for operator to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ create_sub.result.metadata.name }}"
    namespace: "{{ create_sub.result.metadata.namespace }}"
  register: subscription
  until: (subscription.resources[0].status.state is defined) and (subscription.resources[0].status.state == "AtLatestKnown")
  retries: 60
  delay: 10

- name: Wait for CSV to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ subscription.resources[0].status.installedCSV }}"
    namespace: "{{ create_sub.result.metadata.namespace }}"
  register: csv
  until: (csv.resources[0].status.phase is defined) and (csv.resources[0].status.phase == "Succeeded")
  retries: 60
  delay: 10
