- name: Set up Multicluster Engine
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
  roles:
    - {role: "{{ playbook_dir }}/../common/roles/storage", tags: 'provisioning_storage'} # noqa role-name[path]
    - {role: 'provisioning_mirror', tags: 'provisioning_mirror'}
    - {role: 'provisioning_mce', tags: 'provisioning_mce'}
